export const TeamwiseRuns = [
    {
        "team":"Chennai Super Kings",
        "home_wins":"51",
        "away_wins":"49",
        "home_matches":"89",
        "away_matches":"75",
        "home_win_percentage":"57.30337078651685",
        "away_win_percentage":"65.33333333333333",
        "src":"https://www.searchpng.com/wp-content/uploads/2019/02/Chennai-Super-Kings-Logo-PNG-Image-.png",
        "width":"25vw",
        "backgroundcolor":"orangered",
        "borderTop":"8px solid orangered",
        "owner":"Chennai Super Kings Cricket ltd.",
        "coach":"Stephen Fleming",
        "venue":"M. A. Chidambaram Stadium",
        "Captain":"MS Dhoni",
    },
    {
        "team":"Deccan Chargers",
        "home_wins":"18",
        "away_wins":"11",
        "home_matches":"43",
        "away_matches":"32",
        "home_win_percentage":"41.86046511627907",
        "away_win_percentage":"34.375",
        "src":"https://iconape.com/wp-content/files/fq/318355/png/318355.png",
        "width":"27vw",
        "backgroundcolor":"#474f85",
        "borderTop":"8px solid #474f85",
        "owner":"Deccan Chronicle Holdings Ltd.",
        "coach":"Darren Lehmann",
        "venue":"Rajiv Gandhi International Stadium",
        "Captain":"Kumar Sangakkara",
        // "src":require("./images/first-slide.jpg"),
    },
    {
        "team":"Delhi Capitals",
        "home_wins":"3",
        "away_wins":"7",
        "home_matches":"6",
        "away_matches":"10",
        "home_win_percentage":"50.0",
        "away_win_percentage":"70.0",
        "src":"https://cdn.freelogovectors.net/wp-content/uploads/2019/09/delhi-capitals-logo.png",
        "width":"22vw",
        "backgroundcolor": "#539ddb",
        "borderTop":"8px solid #539ddb",
        "owner":"GMR Sports Pvt.Ltd & JSW Sports Pvt.Ltd",
        "coach":"Ricky Ponting",
        "venue":"Feroz Shah Kotla Ground",
        "Captain":"Shreyas Iyer",
    },
    {
        "team":"Delhi Daredevils",
        "home_wins":"25",
        "away_wins":"42",
        "home_matches":"72",
        "away_matches":"89",
        "home_win_percentage":"34.72222222222222",
        "away_win_percentage":"47.19101123595505",
        "src":"https://iconape.com/wp-content/files/rz/319206/svg/319206.svg",
        "width":"25vw",
        "backgroundcolor":"#b71c1c",
        "borderTop":"8px solid #b71c1c",
        "owner":"GMR Sports Pvt.Ltd & JSW Sports Pvt.Ltd",
        "coach":"Ricky Ponting",
        "venue":"Feroz Shah Kotla Ground",
        "Captain":"Shreyas Iyer",
    },
    {
        "team":"Gujarat Lions",
        "home_wins":"1",
        "away_wins":"12",
        "home_matches":"14",
        "away_matches":"16",
        "home_win_percentage":"7.142857142857142",
        "away_win_percentage":"75.0",
        "src":"https://pngimage.net/wp-content/uploads/2018/06/gujarat-lions-logo-png-7.png",
        "width":"20vw",
        "backgroundcolor":"#fdb827",
        "borderTop":"8px solid #fdb827",
        "owner":"Intex Technologies",
        "coach":"Brad Hodge",
        "venue":"Saurashtra Cricket Association Stadium",
        "Captain":"Suresh Raina",
    },
    {
        "team":"Kings XI Punjab",
        "home_wins":"38",
        "away_wins":"44",
        "home_matches":"91",
        "away_matches":"85",
        "home_win_percentage":"41.75824175824176",
        "away_win_percentage":"51.76470588235295",
        "src":"https://i.pinimg.com/originals/25/d5/52/25d552963b3d186a60efc1306870bbd1.png",
        "width":"20vw",
        "backgroundcolor":"#f44336",
        "borderTop":"8px solid #f44336",
        "owner":"KPH Dream Cricket Pvt.Ltd",
        "coach":"Anil Kumble",
        "venue":"IS Bindra Stadium",
        "Captain":"KL Rahul",
    },
    {
        "team":"Kochi Tuskers Kerala",
        "home_wins":"2",
        "away_wins":"4",
        "home_matches":"7",
        "away_matches":"7",
        "home_win_percentage":"28.57142857142857",
        "away_win_percentage":"57.14285714285714",
        "src":"https://i.pinimg.com/originals/fa/fd/1e/fafd1e9044f551631ed856c21ed56339.png",
        "width":"22vw",
        "backgroundcolor":"#9e9e9e",
        "borderTop":"8px solid #9e9e9e",
        "owner":"Kochi Cricket Pvt.Ltd",
        "coach":"Geoff Lawson",
        "venue":"Jawaharlal Nehru Stadium",
        "Captain":"Parthiv Patel",
    },
    {
        "team":"Kolkata Knight Riders",
        "home_wins":"34",
        "away_wins":"58",
        "home_matches":"83",
        "away_matches":"95",
        "home_win_percentage":"40.963855421686745",
        "away_win_percentage":"61.05263157894737",
        "src":"https://i.pinimg.com/originals/2b/4b/cc/2b4bcc707035b560080af1ba0f38d083.jpg",
        "width":"25vw",
        "backgroundcolor":"#673ab7",
        "borderTop":"8px solid #673ab7",
        "owner":"Knight Riders Sports Pvt.Ltd",
        "coach":"Brendon McCullum",
        "venue":"Eden Gardens",
        "Captain":"Eoin Morgan",
    },
    {
        "team":"Mumbai Indians",
        "home_wins":"58",
        "away_wins":"51",
        "home_matches":"101",
        "away_matches":"86",
        "home_win_percentage":"57.42574257425742",
        "away_win_percentage":"59.30232558139535",
        "src":"https://iconape.com/wp-content/files/sr/332362/svg/332362.svg",
        "width":"25vw",
        "backgroundcolor":"#3f51b5",
        "borderTop":"8px solid #3f51b5",
        "owner":"Indiawin SPorts Pvt.Ltd",
        "coach":"Mahela Jayawardene",
        "venue":"Wankhede Stadium",
        "Captain":"Rohit Sharma",
    },
    {
        "team":"Pune Warriors",
        "home_wins":"6",
        "away_wins":"6",
        "home_matches":"20",
        "away_matches":"26",
        "home_win_percentage":"30.0",
        "away_win_percentage":"23.076923076923077",
        "src":"https://i.pinimg.com/originals/bd/3c/3d/bd3c3d726b4761c10478133259ecd27c.png",
        "width":"25vw",
        "backgroundcolor":"#3f51b5",
        "borderTop":"8px solid #3f51b5",
        "owner":"Sahara Group Sports Pvt.Ltd",
        "coach":"Geoff Marsh",
        "venue":"Maharashtra Cricket Association Stadium",
        "Captain":"Angelo Mathews",
    },
    {
        "team":"Rajasthan Royals",
        "home_wins":"29",
        "away_wins":"46",
        "home_matches":"67",
        "away_matches":"80",
        "home_win_percentage":"43.28358208955223",
        "away_win_percentage":"57.49999999999999",
        "src":"https://i.pinimg.com/originals/ce/b7/04/ceb7040289e35b9a2358cf18bb6a9315.png",
        "width":"22vw",
        "backgroundcolor":"#2196f3",
        "borderTop":"8px solid #2196f3",
        "owner":"Royal Multisport Pvt.Ltd",
        "coach":"Andrew McDonald",
        "venue":"Sawai Mansingh Stadium",
        "Captain":"Steve Smith",
    },
    {
        "team":"Rising Pune Supergiant",
        "home_wins":"5",
        "away_wins":"5",
        "home_matches":"8",
        "away_matches":"8",
        "home_win_percentage":"62.5",
        "away_win_percentage":"62.5",
        "src":"https://iplt20cric.com/wp-content/uploads/2016/01/Rising-Pune-Supergiants.jpg",
        "width":"25vw",
        "backgroundcolor":"#9c27b0",
        "borderTop":"8px solid #9c27b0",
        "owner":"RPSG Group",
        "coach":"Stephen Fleming",
        "venue":"Maharashtra Cricket Association Stadium",
        "Captain":"Steve Smith",
    },
    {
        "team":"Royal Challengers Bangalore",
        "home_wins":"35",
        "away_wins":"49",
        "home_matches":"85",
        "away_matches":"95",
        "home_win_percentage":"41.17647058823529",
        "away_win_percentage":"51.578947368421055",
        "src":"https://cdn.freelogovectors.net/wp-content/uploads/2018/08/Royal-Challengers-Bangalore-logo.png",
        "width":"15vw",
        "backgroundcolor":"#ff9100",
        "borderTop":"8px solid #ff9100",
        "owner":"Royal Challengers Sports Pvt.Ltd",
        "coach":"Simon Katich",
        "venue":"M. Chinnaswamy Stadium",
        "Captain":"Virat Kohli",
    },
    {
        "team":"Sunrisers Hyderabad",
        "home_wins":"30",
        "away_wins":"28",
        "home_matches":"63",
        "away_matches":"45",
        "home_win_percentage":"47.61904761904761",
        "away_win_percentage":"62.22222222222222",
        "src":"https://i.pinimg.com/originals/be/39/bf/be39bf6ce491d3840104810a7f055c01.png",
        "width":"25vw",
        "backgroundcolor":"#ff3d00",
        "borderTop":"8px solid #ff3d00",
        "owner":"SUN TV Network",
        "coach":"Trevor Bayliss",
        "venue":"Rajiv Gandhi Intl. Cricket Stadium",
        "Captain":"David Warner",
    },
]
    